name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    env:
      NEXT_PUBLIC_API_POLL_URL: ${{ secrets.API_POLL_URL }}
      NEXT_PUBLIC_API_GENERATE_URL: ${{ secrets.API_GENERATE_URL }}

    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build & Export
        run: |
          pnpm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "ascii-art"
          directory: "out"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
